config/routes.rb
Rails.application.routes.draw do
  resources :testimonials

  resources :user_profiles

  resources :business_profiles

  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

end

app/models/business_profile.rb
class BusinessProfile < ActiveRecord::Base
	has_many :business_users
	has_many :users, through: :business_users
	has_many :testimonials
end

app/controllers/business_profiles_controller.rb
class BusinessProfilesController < ApplicationController
  before_action :set_business_profile, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :show


  # GET /business_profiles
  # GET /business_profiles.json
  def index
    @business_profiles = BusinessProfile.all
  end

  # GET /business_profiles/1
  # GET /business_profiles/1.json
  def show
    @testimonial = Testimonial.new
  end

  # GET /business_profiles/new
  def new
    @business_profile = BusinessProfile.new
  end

  # GET /business_profiles/1/edit
  def edit
  end

  # POST /business_profiles
  # POST /business_profiles.json
  def create
    @business_profile = BusinessProfile.new(business_profile_params)
    @business_profile.users << current_user


    respond_to do |format|
      if @business_profile.save
        format.html { redirect_to @business_profile, notice: 'Business profile was successfully created.' }
        format.json { render :show, status: :created, location: @business_profile }
      else
        format.html { render :new }
        format.json { render json: @business_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_profiles/1
  # PATCH/PUT /business_profiles/1.json
  def update
    respond_to do |format|
      if @business_profile.update(business_profile_params)
        format.html { redirect_to @business_profile, notice: 'Business profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_profile }
      else
        format.html { render :edit }
        format.json { render json: @business_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_profiles/1
  # DELETE /business_profiles/1.json
  def destroy
    @business_profile.destroy
    respond_to do |format|
      format.html { redirect_to business_profiles_url, notice: 'Business profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_profile
      @business_profile = BusinessProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_profile_params
      params.require(:business_profile).permit(:name, :street, :city, :state, :postcode, :country, :phone, :email, :website, :twitter)
    end
end

app/helpers/business_profiles_helper.rb
module BusinessProfilesHelper
end

app/views/business_profiles/_form.html.erb
<%= simple_form_for(@business_profile) do |f| %>
  <% if @business_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_profile.errors.count, "error") %> prohibited this business_profile from being saved:</h2>

      <ul>
      <% @business_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :name %>
     </div>
  <div class="form-group">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/business_profiles/edit.html.erb
<h1>Editing business_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_profile %> |
<%= link_to 'Back', business_profiles_path %>

app/views/business_profiles/index.html.erb
<h1>Listing business_profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Postcode</th>
      <th>Country</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Website</th>
      <th>Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_profiles.each do |business_profile| %>
      <tr>
        <td><%= business_profile.name %></td>
        <td><%= business_profile.street %></td>
        <td><%= business_profile.city %></td>
        <td><%= business_profile.state %></td>
        <td><%= business_profile.postcode %></td>
        <td><%= business_profile.country %></td>
        <td><%= business_profile.phone %></td>
        <td><%= business_profile.email %></td>
        <td><%= business_profile.website %></td>
        <td><%= business_profile.twitter %></td>
        <td><%= link_to 'Show', business_profile %></td>
        <td><%= link_to 'Edit', edit_business_profile_path(business_profile) %></td>
        <td><%= link_to 'Destroy', business_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business profile', new_business_profile_path %>

app/views/business_profiles/new.html.erb
<h1>New business_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', business_profiles_path %>

app/views/business_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
    <div class="panel-body">

      <h1><%= @business_profile.name %></h1>

      <h2>Location</h2>
      <p><%= @business_profile.street %></p>
      <p><%= @business_profile.city %> <%= @business_profile.state %> <%= @business_profile.postcode %> <%= @business_profile.country %></p>

      <h4><span class="fa fa-phone"></span> <%= @business_profile.phone %></h4>
      <h4><span class="fa fa-envelope"></span> <%= @business_profile.email %></h4>
      <h4><i class="fa fa-globe"></i> <%= link_to 'Website', @business_profile.website %></h4>
      <h4><i class="fa fa-twitter"></i> <%= link_to @business_profile.twitter, @business_profile.twitter %></h4>

<%= link_to 'Edit', edit_business_profile_path(@business_profile) %> |
<%= link_to 'Back', business_profiles_path %>
</div></div></div>

<div class="col-md-8">
  <div class="panel panel-default">
    <div class="panel-body">
      <h3>Leave your testimonial</h3>
      <%= render 'testimonials/form' %>
    </div>
  </div>
</div>  