config/routes.rb
Rails.application.routes.draw do
  resources :testimonials

  resources :user_profiles

  resources :business_profiles

  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  belongs_to :user
  belongs_to :business_profile
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)
    @testimonial.user = current_user

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:star_rating, :body, :user_id, :business_profile_id)
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= simple_form_for(@testimonial) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :star_rating, input_html: {class: 'form-control'} %>
  </div>
    <%= f.input :body, label: "Your review", input_html: {class: 'form-control', rows:5} %>
  </div>
<%= f.input :business_profile_id, input_html: {value: @business_profile.id} %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<h1>Listing testimonials</h1>

<table>
  <thead>
    <tr>
      <th>Star rating</th>
      <th>Body</th>
      <th>User</th>
      <th>Business profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testimonials.each do |testimonial| %>
      <tr>
        <td><%= testimonial.star_rating %></td>
        <td><%= testimonial.body %></td>
        <td><%= testimonial.user %></td>
        <td><%= testimonial.business_profile %></td>
        <td><%= link_to 'Show', testimonial %></td>
        <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
        <td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testimonial', new_testimonial_path %>

app/views/testimonials/new.html.erb
<h1>New testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Star rating:</strong>
  <%= @testimonial.star_rating %>
</p>

<p>
  <strong>Body:</strong>
  <%= @testimonial.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @testimonial.user %>
</p>

<p>
  <strong>Business profile:</strong>
  <%= @testimonial.business_profile %>
</p>

<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>